### ISSUE TITLE
terminus not working with faye-websockets 0.6.1

### ISSUE THREAD

**Issue by sjaveed** [jcoglan/terminus#6]
I just cloned the terminus repository (and the submodules needed) but can't seem to follow the video example or the couple of commands mentioned in README.md.  I keep getting an error as follows:

```
$ irb -r ./example/app
1.9.3p194 :001 > extend Capybara::DSL
extending the main object with Capybara::DSL is not recommended!
 => main 
1.9.3p194 :002 > Terminus.browser = {:name => /Chrome/}
 => {:name=>/Chrome/} 
1.9.3p194 :003 > visit '/'
NoMethodError: undefined method `parser' for Faye::WebSocket:Class
    from /Users/sjaveed/rails/terminus/lib/terminus/connector/socket_handler.rb:33:in `initialize'
    from /Users/sjaveed/rails/terminus/lib/terminus/connector/server.rb:105:in `new'
    from /Users/sjaveed/rails/terminus/lib/terminus/connector/server.rb:105:in `accept'
    from /Users/sjaveed/rails/terminus/lib/terminus/connector/server.rb:57:in `request'
    from /Users/sjaveed/rails/terminus/lib/terminus/browser.rb:38:in `ask'
    from /Users/sjaveed/rails/terminus/lib/terminus/browser.rb:223:in `visit'
    from /Users/sjaveed/rails/terminus/lib/capybara/driver/terminus.rb:38:in `visit'
    from /Users/sjaveed/.rvm/gems/ruby-1.9.3-p194@wip/gems/capybara-2.1.0/lib/capybara/session.rb:193:in `visit'
    from /Users/sjaveed/.rvm/gems/ruby-1.9.3-p194@wip/gems/capybara-2.1.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
    from (irb):3
    from /Users/sjaveed/.rvm/rubies/ruby-1.9.3-p194/bin/irb:16:in `<main>'
1.9.3p194 :004 > 
```

The relevant areas from my Gemfile.lock:

```
    faye (0.8.9)
      cookiejar (>= 0.3.0)
      em-http-request (>= 0.3.0)
      eventmachine (>= 0.12.0)
      faye-websocket (>= 0.4.0)
      rack (>= 1.0.0)
      yajl-ruby (>= 1.0.0)
    faye-websocket (0.6.1)
      eventmachine (>= 0.12.0)
      websocket-driver (>= 0.2.0)
```

I tried replacing the call to `Faye::WebSocket.parser(env).new(self)` with `Faye::WebSocket.new(env)` based on a quick perusal of the code but that doesn't seem to be correct either.  The functionality that the parser method was handling now seems to be in Faye::WebSocket::Driver.rack but that's the extent to which I looked.

Any insights?

Thoughts?
